version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      deps:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    target-branch: main
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: main
    open-pull-requests-limit: 5
